# Generated by Django 5.2 on 2025-05-04 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 4, 22, 14, 9, 505916, tzinfo=datetime.timezone.utc
                ),
                verbose_name="дата оплаты",
            ),
        ),
    ]
