# Generated by Django 5.2 on 2025-05-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_payment_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="token",
        ),
    ]
