# Generated by Django 5.2 on 2025-05-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_payment_link_payment_session_id_delete_donation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_amount",
            field=models.PositiveIntegerField(verbose_name="сумма оплаты"),
        ),
    ]
