# Generated by Django 5.2 on 2025-05-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                upload_to="course_previews/", verbose_name="картинка"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                upload_to="lesson_previews/", verbose_name="картинка"
            ),
        ),
    ]
