# Generated by Django 5.2 on 2025-05-04 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0002_alter_course_preview_alter_lesson_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="edu.course",
                verbose_name="курс",
            ),
        ),
    ]
