# Generated by Django 5.2 on 2025-05-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0004_course_author_lesson_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="course_previews/",
                verbose_name="картинка",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lesson_previews/",
                verbose_name="картинка",
            ),
        ),
    ]
